version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: car_rental_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: car_rental_db
      POSTGRES_USER: car_rental_user
      POSTGRES_PASSWORD: car_rental_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
    driver: local

networks:
  car_rental_network:
    driver: bridge 